grails-app/domain/breath/beats/doctor/poc/app/Person.groovy
package breath.beats.doctor.poc.app

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

/**
 * Domain class to define the Person
 * Person can be anyone who is part of Hospital even a patient
 */
@ToString(includeNames = true, ignoreNulls = true)
@EqualsAndHashCode(includeFields = true)
class Person {
    String id
    String uuid
    String firstName
    String middleName
    String lastName
    String gender
    Date dateOfBirth
    String emailAddress
    Integer age
    String primaryContact
    String secondaryContact
    String maritalStatus
    String addressLine1
    String addressLine2
    String addressLine3
    String city
    String state
    String country
    String zipCode
    Role role
    String createdBy
    Date createdOn
    Long version
    static mapping = {
        table( 'bb_person' )
        id column: "person_id", generator: "guid"
        uuid column: "hospital_number"
        firstName column: "first_name"
        middleName column: "middle_name"
        lastName column: "last_name"
        gender column: "gender"
        dateOfBirth column: "date_of_birth"
        emailAddress column: 'email_Address'
        age column: "age"
        primaryContact column: "primary_contact"
        secondaryContact column: "secondary_contact"
        maritalStatus column: "marital_status"
        addressLine1 column: "address_line1"
        addressLine2 column: "address_line2"
        addressLine3 column: "address_line3"
        city column: "city"
        state column: "state_name"
        role column: "role_id"
        country column: "country"
        zipCode column: "zip_code"
        createdBy column: "created_by"
        createdOn column: "created_on"
        version column: "version"
    }
    static constraints = {
        uuid nullable: false
        firstName nullable: false
        middleName nullable: true
        lastName nullable: false
        gender nullable: true
        dateOfBirth nullable: true
        emailAddress nullable: true
        age nullable: true
        primaryContact nullable: false
        secondaryContact nullable: true
        maritalStatus nullable: true
        addressLine1 nullable: true
        addressLine2 nullable: true
        addressLine3 nullable: true
        city nullable: true
        state nullable: true
        role nullable: false
        country nullable: true
        zipCode nullable: true
        createdBy nullable: false
        createdOn nullable: false
    }
}

grails-app/controllers/breath/beats/doctor/poc/app/PersonController.groovy
package breath.beats.doctor.poc.app

import grails.converters.JSON
import grails.transaction.Transactional
import org.apache.log4j.Logger

@Transactional(readOnly = true)
class PersonController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    def breathBeatsCommonService
    Logger logger = Logger.getLogger( this.class.name )

    /**
     * Lists All Persons
     * Method ; GET
     * @return
     */
    def list() {
        def persons = Person.list( [max: Integer.MAX_VALUE] )?.sort() {it.firstName}.sort() {it.lastName}
        def map = [list: persons, count: Person.count()]
        render map as JSON
    }
}

grails-app/views/person/_form.gsp
<%@ page import="breath.beats.doctor.poc.app.Person" %>



<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'addressLine1', 'error')} required">
	<label for="addressLine1">
		<g:message code="person.addressLine1.label" default="Address Line1" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="addressLine1" required="" value="${personInstance?.addressLine1}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'addressLine2', 'error')} required">
	<label for="addressLine2">
		<g:message code="person.addressLine2.label" default="Address Line2" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="addressLine2" required="" value="${personInstance?.addressLine2}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'addressLine3', 'error')} required">
	<label for="addressLine3">
		<g:message code="person.addressLine3.label" default="Address Line3" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="addressLine3" required="" value="${personInstance?.addressLine3}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'age', 'error')} required">
	<label for="age">
		<g:message code="person.age.label" default="Age" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="age" type="number" value="${personInstance.age}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'city', 'error')} required">
	<label for="city">
		<g:message code="person.city.label" default="City" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="city" required="" value="${personInstance?.city}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'country', 'error')} required">
	<label for="country">
		<g:message code="person.country.label" default="Country" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="country" required="" value="${personInstance?.country}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'dateOfBirth', 'error')} required">
	<label for="dateOfBirth">
		<g:message code="person.dateOfBirth.label" default="Date Of Birth" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="dateOfBirth" precision="day"  value="${personInstance?.dateOfBirth}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'firstName', 'error')} required">
	<label for="firstName">
		<g:message code="person.firstName.label" default="First Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="firstName" required="" value="${personInstance?.firstName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'gender', 'error')} required">
	<label for="gender">
		<g:message code="person.gender.label" default="Gender" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="gender" required="" value="${personInstance?.gender}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'lastName', 'error')} required">
	<label for="lastName">
		<g:message code="person.lastName.label" default="Last Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="lastName" required="" value="${personInstance?.lastName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'maritalStatus', 'error')} required">
	<label for="maritalStatus">
		<g:message code="person.maritalStatus.label" default="Marital Status" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="maritalStatus" required="" value="${personInstance?.maritalStatus}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'middleName', 'error')} required">
	<label for="middleName">
		<g:message code="person.middleName.label" default="Middle Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="middleName" required="" value="${personInstance?.middleName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'primaryContact', 'error')} required">
	<label for="primaryContant">
		<g:message code="person.primaryContant.label" default="Primary Contant" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="primaryContant" required="" value="${personInstance?.primaryContant}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'secondaryContact', 'error')} required">
	<label for="secondaryContact">
		<g:message code="person.secondaryContact.label" default="Secondary Contact" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="secondaryContact" required="" value="${personInstance?.secondaryContact}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'state', 'error')} required">
	<label for="state">
		<g:message code="person.state.label" default="State" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="state" required="" value="${personInstance?.state}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: personInstance, field: 'zipCode', 'error')} required">
	<label for="zipCode">
		<g:message code="person.zipCode.label" default="Zip Code" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="zipCode" required="" value="${personInstance?.zipCode}"/>

</div>

grails-app/views/person/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'person.label', default: 'Person')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-person" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-person" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${personInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${personInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:personInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/person/edit.gsp
<%@ page import="breath.beats.doctor.poc.app.Person" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'person.label', default: 'Person')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-person" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-person" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${personInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${personInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:personInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${personInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/person/index.gsp
<%@ page import="breath.beats.doctor.poc.app.Person" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'person.label', default: 'Person')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-person" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-person" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="addressLine1" title="${message(code: 'person.addressLine1.label', default: 'Address Line1')}" />
					
						<g:sortableColumn property="addressLine2" title="${message(code: 'person.addressLine2.label', default: 'Address Line2')}" />
					
						<g:sortableColumn property="addressLine3" title="${message(code: 'person.addressLine3.label', default: 'Address Line3')}" />
					
						<g:sortableColumn property="age" title="${message(code: 'person.age.label', default: 'Age')}" />
					
						<g:sortableColumn property="city" title="${message(code: 'person.city.label', default: 'City')}" />
					
						<g:sortableColumn property="country" title="${message(code: 'person.country.label', default: 'Country')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${personInstanceList}" status="i" var="personInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${personInstance.id}">${fieldValue(bean: personInstance, field: "addressLine1")}</g:link></td>
					
						<td>${fieldValue(bean: personInstance, field: "addressLine2")}</td>
					
						<td>${fieldValue(bean: personInstance, field: "addressLine3")}</td>
					
						<td>${fieldValue(bean: personInstance, field: "age")}</td>
					
						<td>${fieldValue(bean: personInstance, field: "city")}</td>
					
						<td>${fieldValue(bean: personInstance, field: "country")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${personInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/person/show.gsp
<%@ page import="breath.beats.doctor.poc.app.Person" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'person.label', default: 'Person')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-person" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-person" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list person">
			
				<g:if test="${personInstance?.addressLine1}">
				<li class="fieldcontain">
					<span id="addressLine1-label" class="property-label"><g:message code="person.addressLine1.label" default="Address Line1" /></span>
					
						<span class="property-value" aria-labelledby="addressLine1-label"><g:fieldValue bean="${personInstance}" field="addressLine1"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personInstance?.addressLine2}">
				<li class="fieldcontain">
					<span id="addressLine2-label" class="property-label"><g:message code="person.addressLine2.label" default="Address Line2" /></span>
					
						<span class="property-value" aria-labelledby="addressLine2-label"><g:fieldValue bean="${personInstance}" field="addressLine2"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personInstance?.addressLine3}">
				<li class="fieldcontain">
					<span id="addressLine3-label" class="property-label"><g:message code="person.addressLine3.label" default="Address Line3" /></span>
					
						<span class="property-value" aria-labelledby="addressLine3-label"><g:fieldValue bean="${personInstance}" field="addressLine3"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personInstance?.age}">
				<li class="fieldcontain">
					<span id="age-label" class="property-label"><g:message code="person.age.label" default="Age" /></span>
					
						<span class="property-value" aria-labelledby="age-label"><g:fieldValue bean="${personInstance}" field="age"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personInstance?.city}">
				<li class="fieldcontain">
					<span id="city-label" class="property-label"><g:message code="person.city.label" default="City" /></span>
					
						<span class="property-value" aria-labelledby="city-label"><g:fieldValue bean="${personInstance}" field="city"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personInstance?.country}">
				<li class="fieldcontain">
					<span id="country-label" class="property-label"><g:message code="person.country.label" default="Country" /></span>
					
						<span class="property-value" aria-labelledby="country-label"><g:fieldValue bean="${personInstance}" field="country"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personInstance?.dateOfBirth}">
				<li class="fieldcontain">
					<span id="dateOfBirth-label" class="property-label"><g:message code="person.dateOfBirth.label" default="Date Of Birth" /></span>
					
						<span class="property-value" aria-labelledby="dateOfBirth-label"><g:formatDate date="${personInstance?.dateOfBirth}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${personInstance?.firstName}">
				<li class="fieldcontain">
					<span id="firstName-label" class="property-label"><g:message code="person.firstName.label" default="First Name" /></span>
					
						<span class="property-value" aria-labelledby="firstName-label"><g:fieldValue bean="${personInstance}" field="firstName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personInstance?.gender}">
				<li class="fieldcontain">
					<span id="gender-label" class="property-label"><g:message code="person.gender.label" default="Gender" /></span>
					
						<span class="property-value" aria-labelledby="gender-label"><g:fieldValue bean="${personInstance}" field="gender"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personInstance?.lastName}">
				<li class="fieldcontain">
					<span id="lastName-label" class="property-label"><g:message code="person.lastName.label" default="Last Name" /></span>
					
						<span class="property-value" aria-labelledby="lastName-label"><g:fieldValue bean="${personInstance}" field="lastName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personInstance?.maritalStatus}">
				<li class="fieldcontain">
					<span id="maritalStatus-label" class="property-label"><g:message code="person.maritalStatus.label" default="Marital Status" /></span>
					
						<span class="property-value" aria-labelledby="maritalStatus-label"><g:fieldValue bean="${personInstance}" field="maritalStatus"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personInstance?.middleName}">
				<li class="fieldcontain">
					<span id="middleName-label" class="property-label"><g:message code="person.middleName.label" default="Middle Name" /></span>
					
						<span class="property-value" aria-labelledby="middleName-label"><g:fieldValue bean="${personInstance}" field="middleName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personInstance?.primaryContant}">
				<li class="fieldcontain">
					<span id="primaryContant-label" class="property-label"><g:message code="person.primaryContant.label" default="Primary Contant" /></span>
					
						<span class="property-value" aria-labelledby="primaryContant-label"><g:fieldValue bean="${personInstance}" field="primaryContant"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personInstance?.secondaryContact}">
				<li class="fieldcontain">
					<span id="secondaryContact-label" class="property-label"><g:message code="person.secondaryContact.label" default="Secondary Contact" /></span>
					
						<span class="property-value" aria-labelledby="secondaryContact-label"><g:fieldValue bean="${personInstance}" field="secondaryContact"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personInstance?.state}">
				<li class="fieldcontain">
					<span id="state-label" class="property-label"><g:message code="person.state.label" default="State" /></span>
					
						<span class="property-value" aria-labelledby="state-label"><g:fieldValue bean="${personInstance}" field="state"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${personInstance?.zipCode}">
				<li class="fieldcontain">
					<span id="zipCode-label" class="property-label"><g:message code="person.zipCode.label" default="Zip Code" /></span>
					
						<span class="property-value" aria-labelledby="zipCode-label"><g:fieldValue bean="${personInstance}" field="zipCode"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:personInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${personInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>